### PR TITLE
rebase to alpine 3.11 and php7, drop mssql support, and pull in a release zip

### PR DESCRIPTION
**Pull request by thelamer**
Hopefully we can consume built releases if we get a response here: 

https://github.com/projectsend/projectsend/issues/743

This is a major overhaul and might break stuff, MSSQL is def out as ODBC and PHP7 muslc bins don't exist. MS says it is possible next year: 
https://github.com/microsoft/msphpsql/issues/300

Xcache is also out as it is PHP5 only. 

Also swapped to using alpine head modules for apcu and memcached. 

Basic click around and core functionality testing passed, but other than that I do not use this software.

### CODE REVIEW

**Comment by ChadOhman** [comment]
Hello,
My understanding is that r1070 has been out since April 2019, however this image is running r1053. Is there plans to update this image?
Thank you

**Comment by aptalca** [comment]
Did you read the PR description and click on the link? @ChadOhman

**Comment by thelamer** [comment]
@ChadOhman if you could test this out that would be great `lspipepr/projectsend:r1070-pkg-e209e351-pr-15` our PRs spit out consumable builds

**Comment by daklaus** [comment]
@thelamer 
Hi, I just tested the `lspipepr/projectsend:r1070-pkg-e209e351-pr-15` image on my server and it seems to work fine with my previous configuration (used `linuxserver/projectsend` before). It says "updated ProjectSend to version 1070" in the activity log and everything works fine. I didn't test all bug-fixes from the version 1070 but the ones I tested are indeed fixed.
So IMHO I think you can release this package version from the linuxserver pipeline to the official `linuxserver/projectsend` image.

Thanks for maintaining such a nice project with the best docker image factory, linuxserver.io! You are great!

**Comment by aptalca** [comment]
Thanks for testing and for the kind words

**Pull request merged**
